apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: soap-api
  labels:
    app: soap-api
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: soap-api
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
